title: MVKC League History Dashboard
description: Fantasy football league historical data plots
theme: minima
baseurl: "/PocketProtectors"

collections:
  pages:
    output: true
    permalink: /:name/
  subpages:
    output: true
    permalink: /:collection/:path/


social_links:
  github: "https://github.com/TravisBassano/PocketProtectors"